# client side
lambda_module_name: hello_lambda.py
target_zip_name: lambda_package.zip
lambda_runtime: python3.11

# aws side
aws_access_key_id: "AKIAxxxxxxxxxxMDQBA6"
aws_secret_access_key: "eRlv8y14ZxxxxxxxxxxxxxxxxxxxxUnk"
aws_region: "us-east-1"
# ATENCAO: Podemos mudar o terraform para criar como o NOME do módulo
lambda_function_name: hellolambda
s3_bucket_name: hellolambda-dev-bucket
lambda_function_arn: arn:aws:lambda:us-east-1:xxxxxxxxxx:function:hellolambda
